/**
 * Graph Engine Types
 * Tipos base para o sistema de visualização de grafos
 */

import type { Node, Edge, NodeProps, EdgeProps } from 'reactflow';

// ============================================================================
// Tipos de objetos do Plane
// ============================================================================

export type PlaneObjectType = 'issue' | 'cycle' | 'module' | 'page' | 'view';

export type RelationType = 
  | 'blocks' 
  | 'depends_on' 
  | 'parent_of' 
  | 'links_to'
  | 'belongs_to'
  | 'references';

// ============================================================================
// Tipos de nós do grafo
// ============================================================================

export interface GraphNodeMetadata {
  // Common metadata
  title: string;
  description?: string;
  status?: string;
  priority?: 'urgent' | 'high' | 'medium' | 'low' | 'none';
  assignee?: {
    id: string;
    name: string;
    avatar?: string;
  };
  labels?: Array<{
    id: string;
    name: string;
    color: string;
  }>;
  
  // Issue specific
  issueNumber?: string;
  stateId?: string;
  stateColor?: string;
  
  // Cycle specific
  startDate?: string;
  endDate?: string;
  progress?: number;
  
  // Module specific
  completedIssues?: number;
  totalIssues?: number;
  
  // Page specific
  isPublic?: boolean;
  lastUpdated?: string;
  
  // View specific
  queryParams?: Record<string, any>;
  viewType?: 'list' | 'kanban' | 'calendar' | 'gantt' | 'spreadsheet';
}

export interface GraphNode extends Node {
  id: string;
  type?: PlaneObjectType;
  data: {
    label: string;
    metadata: GraphNodeMetadata;
    isExpanded?: boolean;
    isHighlighted?: boolean;
    isSelected?: boolean;
  };
  position: {
    x: number;
    y: number;
  };
  draggable?: boolean;
  selectable?: boolean;
  connectable?: boolean;
  deletable?: boolean;
}

// ============================================================================
// Tipos de arestas do grafo
// ============================================================================

export interface GraphEdgeMetadata {
  createdAt?: string;
  createdBy?: string;
  isAutoGenerated?: boolean;
  strength?: number; // 0-1, para indicar força da relação
}

export interface GraphEdge extends Edge {
  id: string;
  source: string;
  target: string;
  type?: RelationType;
  data?: {
    label?: string;
    metadata?: GraphEdgeMetadata;
    animated?: boolean;
    style?: React.CSSProperties;
  };
  animated?: boolean;
  style?: React.CSSProperties;
  markerEnd?: string;
  markerStart?: string;
}

// ============================================================================
// Tipos de dados do grafo
// ============================================================================

export type LayoutType = 'force' | 'hierarchical' | 'circular' | 'grid' | 'manual';

export interface GraphData {
  nodes: GraphNode[];
  edges: GraphEdge[];
  layout?: LayoutType;
  viewport?: {
    x: number;
    y: number;
    zoom: number;
  };
}

// ============================================================================
// Tipos de filtros
// ============================================================================

export interface GraphFilters {
  types?: PlaneObjectType[];
  statuses?: string[];
  priorities?: string[];
  assignees?: string[];
  labels?: string[];
  dateRange?: {
    start: string;
    end: string;
  };
  searchQuery?: string;
}

// ============================================================================
// Tipos de configuração
// ============================================================================

export interface GraphConfig {
  layout: LayoutType;
  showMinimap: boolean;
  showControls: boolean;
  showBackground: boolean;
  enablePanOnDrag: boolean;
  enableZoom: boolean;
  enableNodeDrag: boolean;
  enableEdgeCreation: boolean;
  maxZoom: number;
  minZoom: number;
  fitViewOptions?: {
    padding?: number;
    includeHiddenNodes?: boolean;
    minZoom?: number;
    maxZoom?: number;
    duration?: number;
  };
}

// ============================================================================
// Tipos de eventos
// ============================================================================

export interface GraphNodeClickEvent {
  node: GraphNode;
  event: React.MouseEvent;
}

export interface GraphEdgeClickEvent {
  edge: GraphEdge;
  event: React.MouseEvent;
}

export interface GraphConnectionEvent {
  source: string;
  target: string;
  sourceHandle?: string | null;
  targetHandle?: string | null;
}

export interface GraphChangeEvent {
  nodes?: GraphNode[];
  edges?: GraphEdge[];
  viewport?: {
    x: number;
    y: number;
    zoom: number;
  };
}

// ============================================================================
// Tipos de props para componentes customizados
// ============================================================================

export interface IssueNodeProps extends NodeProps {
  data: GraphNode['data'] & {
    issueNumber: string;
    stateColor: string;
  };
}

export interface CycleNodeProps extends NodeProps {
  data: GraphNode['data'] & {
    startDate: string;
    endDate: string;
    progress: number;
  };
}

export interface ModuleNodeProps extends NodeProps {
  data: GraphNode['data'] & {
    completedIssues: number;
    totalIssues: number;
  };
}

export interface PageNodeProps extends NodeProps {
  data: GraphNode['data'] & {
    isPublic: boolean;
    lastUpdated: string;
  };
}

export interface ViewNodeProps extends NodeProps {
  data: GraphNode['data'] & {
    viewType: GraphNodeMetadata['viewType'];
    queryParams: Record<string, any>;
  };
}

// ============================================================================
// Tipos de resposta da API
// ============================================================================

export interface GraphApiResponse {
  data: GraphData;
  metadata?: {
    totalNodes: number;
    totalEdges: number;
    timestamp: string;
    scope: string;
  };
  error?: {
    message: string;
    code: string;
  };
}

export interface RelationshipCreateRequest {
  sourceId: string;
  targetId: string;
  type: RelationType;
  metadata?: Record<string, any>;
}

export interface RelationshipDeleteRequest {
  relationshipId: string;
}

export interface GraphLayoutUpdateRequest {
  nodes: Array<{
    id: string;
    position: {
      x: number;
      y: number;
    };
  }>;
  viewport?: {
    x: number;
    y: number;
    zoom: number;
  };
}

// ============================================================================
// Tipos utilitários
// ============================================================================

export type NodeStyleGetter = (node: GraphNode) => React.CSSProperties;
export type EdgeStyleGetter = (edge: GraphEdge) => React.CSSProperties;

export interface GraphTheme {
  nodes: {
    [K in PlaneObjectType]: {
      backgroundColor: string;
      borderColor: string;
      textColor: string;
      iconColor: string;
    };
  };
  edges: {
    [K in RelationType]: {
      strokeColor: string;
      strokeWidth: number;
      strokeDasharray?: string;
      markerColor: string;
    };
  };
  background: {
    backgroundColor: string;
    patternColor: string;
  };
  minimap: {
    backgroundColor: string;
    maskColor: string;
    nodeColor: string;
  };
}

// Re-export React Flow types that we use
export type {
  Node,
  Edge,
  NodeProps,
  EdgeProps,
  Connection,
  ReactFlowInstance,
  NodeChange,
  EdgeChange,
  Viewport,
  OnNodesChange,
  OnEdgesChange,
  OnConnect,
} from 'reactflow';